language: ruby

rvm:
  - 1.9.3

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - "bundle rake jasmine:ci"
  - "bundle rspec spec"
  - "bundle cucumber features"
